FROM gradle:jdk11 AS build

ARG WORK_DIR=/workspace/app
ARG JAR_DIR=/workspace/jar
COPY . ${WORK_DIR}
WORKDIR ${WORK_DIR}

RUN gradle --version
RUN gradle clean
RUN gradle build

COPY build/libs/github-issue-tracker-*.jar ${JAR_DIR}/app.jar



FROM azul/zulu-openjdk-alpine:11

COPY --from=build ${JAR_DIR}/app.jar .

ENTRYPOINT ["java", "-jar", "app.jar", "-noverify"]
