# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 11

    - name: Lint
      run: ./gradlew lintKotlin

    - name: execute gradle build
      run: ./gradlew build

    - name: publish sonarqube report
      run: |
        git fetch --prune --unshallow
        ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

    - name: build docker image
      run: docker build . -t github-issue-tracker:latest

    - name: Scan with Phonito Security
      uses: phonito/phonito-scanner-action@master
      with:
        image: github-issue-tracker:latest
        phonito-token: '${{ secrets.PHONITO_TOKEN }}'

    - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: dripto-git-01
        heroku_email: driptaroop.das@gmail.com
        usedocker: true #OPTIONAL and DEFAULT - false

    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SCRIPT_FILEPATH: ./mail/email-sending-script.js

    - name: Send Push Notification
      uses: techulus/push-github-action@v0.0.2
      env:
        API_KEY: ${{ secrets.TECHULUS_API_KEY }}
        MESSAGE: "Build completed successfully"
