name: PR-Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: verify gradle wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11

    - name: ktlint
      uses: ScaCap/action-ktlint@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review # Change reporter

    - name: Lint
      run: ./gradlew lintKotlin

    - name: execute gradle build
      run: ./gradlew build

    - name: build docker image
      run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
